mysql:
  host: 127.0.0.1
  port: 3306
  username: root
  password: 123456
  database: test
  charset: utf8mb4

redis:
  host: 127.0.0.1
  port: 6379
  password:
  database: 0

jwt:
  secretKey: hello
  accessExp: 3600
  refreshExp: 7200